# 🧼 Cleaning Dirty Data (Missing Values & Type Fixes)

## 🔹 LEARNING GOALS:
- Detect and count missing values (`NaN`)
- Fill or drop missing data
- Convert column data types safely
- Understand the difference between `NaN`, `None`, `""`, and type mismatches

### 🧪 1. Load a Messy Dataset

In [18]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", None],
    "Age": ["25", "thirty", 35, np.nan, None],
    "Signup Date": ["2022-01-01", "not a date", "2022/03/01","April 5, 2022", None],
    "Score": [95.5, None, 88.0, 92.5, ""],
    "Gender": ["Female", "Male", None, "", "Male"]
}

df = pd.DataFrame(data)
df

      Name     Age    Signup Date Score  Gender
0    Alice      25     2022-01-01  95.5  Female
1      Bob  thirty     not a date  None    Male
2  Charlie      35     2022/03/01  88.0    None
3    David     NaN  April 5, 2022  92.5
4     None    None           None          Male

### 🧯 2. Detecting Missing or Broken Values

In [19]:
df.isnull()

    Name    Age  Signup Date  Score  Gender
0  False  False        False  False   False
1  False  False        False   True   False
2  False  False        False  False    True
3  False   True        False  False   False
4   True   True         True  False   False

In [20]:
df.isnull().sum()

Name           1
Age            2
Signup Date    1
Score          1
Gender         1
dtype: int64

In [21]:
df[df.isnull().any(axis=1)]

      Name     Age    Signup Date Score Gender
1      Bob  thirty     not a date  None   Male
2  Charlie      35     2022/03/01  88.0   None
3    David     NaN  April 5, 2022  92.5
4     None    None           None         Male

### 🧹 3. Cleaning Strategy Options

In [24]:
df.fillna({
    "Name": "Unknown",
    "Age": -1,
    "Signup Date": "1970-01-01",
    "Score": 0.0,
    "Gender": "Unknown"
})

      Name     Age    Signup Date Score   Gender
0    Alice      25     2022-01-01  95.5   Female
1      Bob  thirty     not a date   0.0     Male
2  Charlie      35     2022/03/01  88.0  Unknown
3    David      -1  April 5, 2022  92.5
4  Unknown      -1     1970-01-01           Male

In [25]:
df.dropna()

    Name Age Signup Date Score  Gender
0  Alice  25  2022-01-01  95.5  Female

### 🧬 4. Data Type Fixes

In [26]:
df.dtypes

Name           object
Age            object
Signup Date    object
Score          object
Gender         object
dtype: object

In [27]:
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Score"] = pd.to_numeric(df["Score"], errors="coerce")
df["Signup Date"] = pd.to_datetime(df["Signup Date"], errors="coerce")
df.dtypes

Name                   object
Age                   float64
Signup Date    datetime64[ns]
Score                 float64
Gender                 object
dtype: object

### 🩹 5. Impute (Fill In) Fixed Missing Values

In [28]:
df["Age"].fillna(df["Age"].median(), inplace=True)
df["Score"].fillna(df["Score"].mean(), inplace=True)

/tmp/ipython-input-1713118361.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Age"].fillna(df["Age"].median(), inplace=True)
/tmp/ipython-input-1713118361.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Score"].fillna(df["Score"].mean(), inplace=True)

In [29]:
df["Signup Date"].fillna(df["Signup Date"].min(), inplace=True)

/tmp/ipython-input-3000949103.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Signup Date"].fillna(df["Signup Date"].min(), inplace=True)

In [30]:
df["Name"].fillna("Unknown", inplace=True)

/tmp/ipython-input-626038248.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Name"].fillna("Unknown", inplace=True)

### 🤓 6. Cleaned Data Review

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         5 non-null      object
 1   Age          5 non-null      float64
 2   Signup Date  5 non-null      datetime64[ns]
 3   Score        5 non-null      float64
 4   Gender       4 non-null      object
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 332.0+ bytes

In [32]:
df.describe(include="all")

         Name        Age          Signup Date     Score Gender
count       5   5.000000                    5   5.00000      4
unique      5        NaN                  NaN       NaN      3
top     Alice        NaN                  NaN       NaN   Male
freq        1        NaN                  NaN       NaN      2
mean      NaN  30.000000  2022-01-01 00:00:00  92.00000    NaN
min       NaN  25.000000  2022-01-01 00:00:00  88.00000    NaN
25%       NaN  30.000000  2022-01-01 00:00:00  92.00000    NaN
50%       NaN  30.000000  2022-01-01 00:00:00  92.00000    NaN
75%       NaN  30.000000  2022-01-01 00:00:00  92.50000    NaN
max       NaN  35.000000  2022-01-01 00:00:00  95.50000    NaN
std       NaN   3.535534                  NaN   2.66927    NaN

### 🧪 Try It Yourself

Modify the `data` dictionary at the top of this notebook. Add:
- A new column with some `None` and `""` values
- At least one row with all columns filled incorrectly
Then re-run the notebook and fix it step-by-step.

### 🧠 Mini-Challenge

> 🗂 Load `"data/survey.csv"` and:
- Identify which columns have missing values
- Use `.isnull().sum()` to get a null report
- Use a mix of `.fillna()`, `.dropna()`, and `pd.to_numeric()` or `pd.to_datetime()` to clean it
- Print a summary with `.info()` and `.describe()`

In [44]:
df = pd.read_csv("/students.csv")
print(df.isnull().sum())

print("Info:", df.info())

print("\nStats: ", df.describe())

print("\n", df.head())

first_name       0
last_name        0
math_score       0
science_score    0
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   first_name     50 non-null     object
 1   last_name      50 non-null     object
 2   math_score     50 non-null     int64
 3   science_score  50 non-null     int64
dtypes: int64(2), object(2)
memory usage: 1.7+ KB
Info: None

Stats:         math_score  science_score
count    50.00000      50.000000
mean     77.56000      80.240000
std      12.17753      11.659384
min      60.00000      62.000000
25%      66.25000      73.000000
50%      75.50000      78.000000
75%      87.00000      89.000000
max     100.00000     100.000000

   first_name last_name  math_score  science_score
0   Danielle      Wood         100             95
1      Angel     Clark          67             78
2     Joshua     Adams          61            100
3    Jeffrey    Zuniga          77             99
4       Jill      Wong          75             83

### 📝 Summary

| Concept        | Tool/Function                      |
|----------------|------------------------------------|
| Detect nulls   | `df.isnull()`, `df.isnull().sum()` |
| Drop rows      | `df.dropna()`                      |
| Fill values    | `df.fillna()`                      |
| Convert types  | `pd.to_numeric()`, `pd.to_datetime()` |
| Replace values | `df.replace()`                     |