# 🧱 Column Operations: Creating, Renaming, and Dropping Columns

## 🔹 LEARNING GOALS:
- Create new columns using calculations or functions
- Rename one or multiple columns
- Drop unwanted columns safely
- Apply functions across columns using `.apply()` and lambdas

### 🏗️ 1. Setup and Sample Data

In [1]:
import pandas as pd

data = {
    "first_name": ["Alice", "Bob", "Charlie", "David"],
    "last_name": ["Smith", "Jones", "Brown", "Wilson"],
    "math_score": [85, 90, 78, 92],
    "science_score": [88, 85, 82, 95]
}

df = pd.DataFrame(data)
df

  first_name last_name  math_score  science_score
0      Alice     Smith          85             88
1        Bob     Jones          90             85
2    Charlie     Brown          78             82
3      David    Wilson          92             95

### ➕ 2. Creating New Columns

In [2]:
# Simple column arithmetic
df["average_score"] = (df["math_score"] + df["science_score"]) / 2
df

  first_name last_name  math_score  science_score  average_score
0      Alice     Smith          85             88           86.5
1        Bob     Jones          90             85           87.5
2    Charlie     Brown          78             82           80.0
3      David    Wilson          92             95           93.5

In [3]:
# Create full name column
df["full_name"] = df["first_name"] + " " + df["last_name"]
df

,first_name,last_name,math_score,science_score,average_score,full_name
0,Alice,Smith,85,88,86.5,Alice Smith
1,Bob,Jones,90,85,87.5,Bob Jones
2,Charlie,Brown,78,82,80.0,Charlie Brown
3,David,Wilson,92,95,93.5,David Wilson

### ✍️ 3. Renaming Columns

In [4]:
# Rename a single column
df.rename(columns={"math_score": "Math", "science_score": "Science"}, inplace=True)
df

  first_name last_name  Math  Science  average_score      full_name
0      Alice     Smith    85       88           86.5    Alice Smith
1        Bob     Jones    90       85           87.5      Bob Jones
2    Charlie     Brown    78       82           80.0  Charlie Brown
3      David    Wilson    92       95           93.5   David Wilson

In [5]:
# Rename all columns to uppercase
df.columns = [col.upper() for col in df.columns]
df

  FIRST_NAME LAST_NAME  MATH  SCIENCE  AVERAGE_SCORE      FULL_NAME
0      Alice     Smith    85       88           86.5    Alice Smith
1        Bob     Jones    90       85           87.5      Bob Jones
2    Charlie     Brown    78       82           80.0  Charlie Brown
3      David    Wilson    92       95           93.5   David Wilson

### ❌ 4. Dropping Columns

In [6]:
# Drop by name
df.drop(columns=["FULL_NAME"], inplace=True)
df

  FIRST_NAME LAST_NAME  MATH  SCIENCE  AVERAGE_SCORE
0      Alice     Smith    85       88           86.5
1        Bob     Jones    90       85           87.5
2    Charlie     Brown    78       82           80.0
3      David    Wilson    92       95           93.5

### 🔁 5. Applying Functions Across Columns

In [7]:
# Categorize based on average score
def grade(score):
    if score >= 90:
        return "A"
    elif score >= 80:
        return "B"
    else:
        return "C"

df["GRADE"] = df["AVERAGE_SCORE"].apply(grade)
df

  FIRST_NAME LAST_NAME  MATH  SCIENCE  AVERAGE_SCORE GRADE
0      Alice     Smith    85       88           86.5     B
1        Bob     Jones    90       85           87.5     B
2    Charlie     Brown    78       82           80.0     B
3      David    Wilson    92       95           93.5     A

### 🧪 Try It Yourself

- Add a new column called `"NAME_LENGTH"` that contains the length of each `FIRST_NAME`
- Create a column `"MATH_PLUS_5"` which is the math score + 5 points bonus

In [12]:
# 1.
df["NAME_LENGTH"] = df["FIRST_NAME"].apply(len)
df

# 2.
df["MATH_PLUS_5"] = df["MATH"] + 5
df

,FIRST_NAME,LAST_NAME,MATH,SCIENCE,AVERAGE_SCORE,GRADE,NAME_LENGTH,MATH_PLUS_5
0,Alice,Smith,85,88,86.5,B,5,90
1,Bob,Jones,90,85,87.5,B,3,95
2,Charlie,Brown,78,82,80.0,B,7,83
3,David,Wilson,92,95,93.5,A,5,97

### 🧠 Mini-Challenge

> Load `"data/students.csv"` and:
- Create a `"total_score"` column by summing up all numeric test columns
- Rename any columns that contain spaces (e.g., `"Test 1"`) to use underscores
- Drop any column that contains only `NaN` values

In [26]:
df = pd.read_csv("/content/students.csv")

# 1.
df["total_score"] = df["math_score"] + df["science_score"]

# Drop any column that contains only NaN values.
df.dropna(axis=1, how="all", inplace=True)
df

     first_name  last_name  math_score  science_score  total_score
0      Danielle       Wood         100             95          195
1         Angel      Clark          67             78          145
2        Joshua      Adams          61            100          161
3       Jeffrey     Zuniga          77             99          176
4          Jill       Wong          75             83          158
5         Erica      Lynch          74             96          170
6      Patricia    Jackson          68             72          140
7   Christopher     Daniel          66             64          130
8        Robert     Martin          94             62          156
9       Anthony       Gray          65             74          139
10      Jeffery       Mayo          97             78          175
11      William     Bowman          87             65          152
12      Anthony    Hawkins          62             74          136
13        James      Cohen          61             66          127
14        Debra    Cameron          65             84          149
15          Amy    Parsons          73             77          150
16      Jeffrey      Perez          74             89          163
17      Bridget    Johnson          92            100          192
18         Lisa    Stewart          98             83          181
19         Adam      Adams          61             70          131
20        Linda      Clark          95             83          178
21        Helen       Hahn          72             82          154
22      Matthew     Walter          94             73          167
23         Eric    Edwards          86             77          163
24        Susan       Rios          74             64          138
25      Matthew     Foster          88             98          186
26  Christopher      Rocha          97            100          197
27        Colin      Ellis          77             70          147
28      Melanie      Baker          60             94          154
29    Cassandra     Wright          70             75          145
30      Lindsay    Hoffman          87             70          157
31      Jessica      Baker          81             89          170
32       Amanda   Richards          77             84          161
33       Teresa      Hurst          69             77          146
34     Nicholas       Ross          73            100          173
35       Andrea   Robinson          81             95          176
36        Maria     Bright          66             74          140
37    Christine      Hicks          65             80          145
38     Michelle      Davis          84             63          147
39      Barbara   Williams          66             74          140
40        Janet  Rodriguez          82             62          144
41      Brandon     Burton          82             80          162
42       Jeremy     Conner          98             85          183
43        Keith  Henderson          76             77          153
44  Christopher      Brown          62             64          126
45        Jesse      James          89             73          162
46        Craig    Ferrell          94             96          190
47       Joshua       Rice          67             80          147
48      Cynthia     Maddox          84             73          157
49      Michael   Valencia          65             91          156

### 📝 Summary

| Action             | Method                                |
|--------------------|----------------------------------------|
| Create column       | `df["new"] = ...`                     |
| Rename column(s)    | `df.rename(columns={...})`            |
| Rename all columns  | `df.columns = [...]`                 |
| Drop column(s)      | `df.drop(columns=[...])`              |
| Apply function      | `df["col"].apply(func)`               |